development:
  TWITTER_APP_ID: 'TWITTER_APP_ID--FAKE'
  TWITTER_APP_SECRET: 'TWITTER_APP_SECRET--FAKE'
  FACEBOOK_APP_ID: 'FACEBOOK_APP_ID--FAKE'
  FACEBOOK_APP_SECRET: 'FACEBOOK_APP_SECRET--FAKE'
  INSTAGRAM_APP_ID: 'INSTAGRAM_APP_ID--FAKE'
  INSTAGRAM_APP_SECRET: 'INSTAGRAM_APP_SECRET--FAKE'

  MIXPANEL_TOKEN: 'MIXPANEL_TOKEN--FAKE'

  AWS_BUCKET_NAME: 'AWS_BUCKET_NAME--FAKE'
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID--FAKE'
  AWS_ACCESS_KEY_SECRET: 'AWS_ACCESS_KEY_SECRET--FAKE'

test:
  TWITTER_APP_ID: 'TWITTER_APP_ID--FAKE'
  TWITTER_APP_SECRET: 'TWITTER_APP_SECRET--FAKE'
  FACEBOOK_APP_ID: 'FACEBOOK_APP_ID--FAKE'
  FACEBOOK_APP_SECRET: 'FACEBOOK_APP_SECRET--FAKE'
  INSTAGRAM_APP_ID: 'INSTAGRAM_APP_ID--FAKE'
  INSTAGRAM_APP_SECRET: 'INSTAGRAM_APP_SECRET--FAKE'

  MIXPANEL_TOKEN: 'MIXPANEL_TOKEN--FAKE'

  AWS_BUCKET_NAME: 'AWS_BUCKET_NAME--FAKE'
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID--FAKE'
  AWS_ACCESS_KEY_SECRET: 'AWS_ACCESS_KEY_SECRET--FAKE'

staging:
  TWITTER_APP_ID: 'TWITTER_APP_ID--FAKE--DO-NOT-PUSH'
  TWITTER_APP_SECRET: 'TWITTER_APP_SECRET--FAKE--DO-NOT-PUSH'
  FACEBOOK_APP_ID: 'FACEBOOK_APP_ID--FAKE--DO-NOT-PUSH'
  FACEBOOK_APP_SECRET: 'FACEBOOK_APP_SECRET--FAKE--DO-NOT-PUSH'
  INSTAGRAM_APP_ID: 'INSTAGRAM_APP_ID--FAKE--DO-NOT-PUSH'
  INSTAGRAM_APP_SECRET: 'INSTAGRAM_APP_SECRET--FAKE--DO-NOT-PUSH'

  MIXPANEL_TOKEN: 'MIXPANEL_TOKEN--FAKE--DO-NOT-PUSH'

  AWS_BUCKET_NAME: 'AWS_BUCKET_NAME--FAKE--DO-NOT-PUSH'
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID--FAKE--DO-NOT-PUSH'
  AWS_ACCESS_KEY_SECRET: 'AWS_ACCESS_KEY_SECRET--FAKE--DO-NOT-PUSH'

production:
  TWITTER_APP_ID: 'TWITTER_APP_ID--FAKE--DO-NOT-PUSH'
  TWITTER_APP_SECRET: 'TWITTER_APP_SECRET--FAKE--DO-NOT-PUSH'
  FACEBOOK_APP_ID: 'FACEBOOK_APP_ID--FAKE--DO-NOT-PUSH'
  FACEBOOK_APP_SECRET: 'FACEBOOK_APP_SECRET--FAKE--DO-NOT-PUSH'
  INSTAGRAM_APP_ID: 'INSTAGRAM_APP_ID--FAKE--DO-NOT-PUSH'
  INSTAGRAM_APP_SECRET: 'INSTAGRAM_APP_SECRET--FAKE--DO-NOT-PUSH'

  MIXPANEL_TOKEN: 'MIXPANEL_TOKEN--FAKE--DO-NOT-PUSH'

  AWS_BUCKET_NAME: 'AWS_BUCKET_NAME--FAKE--DO-NOT-PUSH'
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID--FAKE--DO-NOT-PUSH'
  AWS_ACCESS_KEY_SECRET: 'AWS_ACCESS_KEY_SECRET--FAKE--DO-NOT-PUSH'
